name = "booktrails"
main = "./dist/_worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[env.production]
routes = [
  { pattern = "booktrails.rabbitholes.garden/*", zone_name = "rabbitholes.garden" }
]

# For development
[env.development]
name = "booktrails-dev"